# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e16637bfd7a5e3ebe8795ccbb4f3931394088f6847c9c794ab3ecc76751c3a191f255882282f82d806ca3f2d473633dfe7db8b2e9c60f4544dabdd9c7bc43e

test:
  secret_key_base: caad3c5670ed39c0afaa6d77669e3938028ee4d8a2e53b1a69e735f8bde56ba411797d745b2d783f8a32fdd9b4fa57e9cd568dccedcc9d9757f43dbeab9f2a98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
